# Gitpod Configuration File
# Learn more: https://www.gitpod.io/docs/configure/projects/gitpod-yaml

tasks:
  - name: Install Dependencies
    init: pip install --no-cache-dir -r requirements.txt
    command: python app.py

# Expose Flask app on port 5000
ports:
  - port: 5000
    onOpen: open-browser
